version: "3"

services:
  po-agent:
    build: .
    init: true
    working_dir: /app
    env_file: ./.env
    restart: always
    security_opt:
      - seccomp:unconfined
    networks:
      - ast
    volumes:
      - ./:/app:rw
      - ~/.ssh:/tmp/ssh:ro
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config:ro # Optional: Mount SSH config
    command: >
      /bin/sh -c "
        cp -r /tmp/ssh ~/.ssh &&
        chown -R node:node ~/.ssh &&
        chmod 600 ~/.ssh/id_ed25519 &&
        chmod 644 ~/.ssh/config &&
        chmod 644 ~/.ssh/id_ed25519.pub &&
        npx puppeteer browsers install chrome &&
        npm run start:po
      "
  architect-agent:
    build: .
    init: true
    working_dir: /app
    env_file: ./.env
    restart: always
    security_opt:
      - seccomp:unconfined
    networks:
      - ast
    volumes:
      - ./:/app:rw
      - ~/.ssh:/tmp/ssh:ro
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config:ro # Optional: Mount SSH config
    command: >
      /bin/sh -c "
        cp -r /tmp/ssh ~/.ssh &&
        chown -R node:node ~/.ssh &&        
        chmod 600 ~/.ssh/id_ed25519 &&
        chmod 644 ~/.ssh/config &&
        chmod 644 ~/.ssh/id_ed25519.pub &&
        npx puppeteer browsers install chrome &&
        npm run start:architect
      "
  dev-agent:
    build: .
    init: true
    working_dir: /app
    env_file: ./.env
    restart: always
    security_opt:
      - seccomp:unconfined
    networks:
      - ast
    volumes:
      - ./:/app:rw
      - ~/.ssh:/tmp/ssh:ro
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config:ro # Optional: Mount SSH config
    command: >
      /bin/sh -c "
        cp -r /tmp/ssh ~/.ssh &&
        chown -R node:node ~/.ssh &&        
        chmod 600 ~/.ssh/id_ed25519 &&
        chmod 644 ~/.ssh/config &&
        chmod 644 ~/.ssh/id_ed25519.pub &&
        npx puppeteer browsers install chrome &&
        npm run start:dev
      "

networks:
  ast:
    driver: bridge
