# Use root/example as user/password credentials
version: "3"

services:
  db:
    container_name: ast-mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ast_test_db
    networks:
      - ast

networks:
  ast:
    driver: bridge
